// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public interface ColumnarCacheFilesInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orc.proto.ColumnarCacheFilesInfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
