// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public interface ColumnarDeltaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orc.proto.ColumnarDeltaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * response status
   * </pre>
   *
   * <code>.orc.proto.ColumnarDeltaResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * response status
   * </pre>
   *
   * <code>.orc.proto.ColumnarDeltaResponse.Status status = 1;</code>
   * @return The status.
   */
  ColumnarDeltaResponse.Status getStatus();

  /**
   * <pre>
   * byte stream
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   * error message
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  String getErrorMessage();
  /**
   * <pre>
   * error message
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
