// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public interface ColumnarCacheFilesInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orc.proto.ColumnarCacheFilesInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .orc.proto.FileInfo files = 1;</code>
   */
  java.util.List<FileInfo>
      getFilesList();
  /**
   * <code>repeated .orc.proto.FileInfo files = 1;</code>
   */
  FileInfo getFiles(int index);
  /**
   * <code>repeated .orc.proto.FileInfo files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .orc.proto.FileInfo files = 1;</code>
   */
  java.util.List<? extends FileInfoOrBuilder>
      getFilesOrBuilderList();
  /**
   * <code>repeated .orc.proto.FileInfo files = 1;</code>
   */
  FileInfoOrBuilder getFilesOrBuilder(
      int index);
}
