// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public interface ColumnarDeltaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orc.proto.ColumnarDeltaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * delta file name: csv or del
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  String getFileName();
  /**
   * <pre>
   * delta file name: csv or del
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <pre>
   * read offset
   * </pre>
   *
   * <code>int32 offset = 2;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <pre>
   * read length
   * </pre>
   *
   * <code>int32 length = 3;</code>
   * @return The length.
   */
  int getLength();
}
