// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public final class DeltaProto {
  private DeltaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orc_proto_ColumnarDeltaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orc_proto_ColumnarDeltaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orc_proto_ColumnarDeltaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orc_proto_ColumnarDeltaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orc_proto_ColumnarCacheFilesInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orc_proto_ColumnarCacheFilesInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orc_proto_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orc_proto_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orc_proto_ColumnarCacheFilesInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orc_proto_ColumnarCacheFilesInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021delta_proto.proto\022\torc.proto\"I\n\024Column" +
      "arDeltaRequest\022\021\n\tfile_name\030\001 \001(\t\022\016\n\006off" +
      "set\030\002 \001(\005\022\016\n\006length\030\003 \001(\005\"\346\001\n\025ColumnarDe" +
      "ltaResponse\0227\n\006status\030\001 \001(\0162\'.orc.proto." +
      "ColumnarDeltaResponse.Status\022\014\n\004data\030\002 \001" +
      "(\014\022\025\n\rerror_message\030\003 \001(\t\"o\n\006Status\022\006\n\002O" +
      "K\020\000\022\024\n\020INVALID_ARGUMENT\020\001\022\r\n\tNOT_FOUND\020\002" +
      "\022\022\n\016DATA_CORRUPTED\020\003\022\020\n\014RATE_LIMITED\020\004\022\022" +
      "\n\016INTERNAL_ERROR\020\005\"\037\n\035ColumnarCacheFiles" +
      "InfoRequest\"2\n\010FileInfo\022\021\n\tfile_name\030\001 \001" +
      "(\t\022\023\n\013file_length\030\002 \001(\005\"D\n\036ColumnarCache" +
      "FilesInfoResponse\022\"\n\005files\030\001 \003(\0132\023.orc.p" +
      "roto.FileInfo2\341\001\n\024ColumnarDeltaService\022Z" +
      "\n\023ColumnarDeltaStream\022\037.orc.proto.Column" +
      "arDeltaRequest\032 .orc.proto.ColumnarDelta" +
      "Response0\001\022m\n\026ColumnarCacheFilesInfo\022(.o" +
      "rc.proto.ColumnarCacheFilesInfoRequest\032)" +
      ".orc.proto.ColumnarCacheFilesInfoRespons" +
      "eB%\n!com.alibaba.polardbx.rpc.columnarP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orc_proto_ColumnarDeltaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orc_proto_ColumnarDeltaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orc_proto_ColumnarDeltaRequest_descriptor,
        new String[] { "FileName", "Offset", "Length", });
    internal_static_orc_proto_ColumnarDeltaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orc_proto_ColumnarDeltaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orc_proto_ColumnarDeltaResponse_descriptor,
        new String[] { "Status", "Data", "ErrorMessage", });
    internal_static_orc_proto_ColumnarCacheFilesInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_orc_proto_ColumnarCacheFilesInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orc_proto_ColumnarCacheFilesInfoRequest_descriptor,
        new String[] { });
    internal_static_orc_proto_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_orc_proto_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orc_proto_FileInfo_descriptor,
        new String[] { "FileName", "FileLength", });
    internal_static_orc_proto_ColumnarCacheFilesInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_orc_proto_ColumnarCacheFilesInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orc_proto_ColumnarCacheFilesInfoResponse_descriptor,
        new String[] { "Files", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
