// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta_proto.proto

package com.alibaba.polardbx.rpc.columnar;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orc.proto.FileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int32 file_length = 2;</code>
   * @return The fileLength.
   */
  int getFileLength();
}
