package com.alibaba.polardbx.qatest.NotThreadSafe;

import com.alibaba.polardbx.qatest.AutoReadBaseTestCase;
import com.alibaba.polardbx.qatest.util.JdbcUtil;
import org.apache.commons.lang.StringUtils;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Integration test for information_schema.physical_index_usage and logical_index_usage.
 * <p>
 * Tests use real performance_schema.table_io_waits_summary_by_index_usage data
 * generated by creating tables, inserting rows, and running queries that exercise indexes.
 */
public class IndexUsageIntegrationTest extends AutoReadBaseTestCase {

    private static final String TEST_TABLE = "idx_usage_test_tbl";
    private static final String TEST_GSI = "idx_usage_test_gsi";
    private static final String LOCAL_INDEX_NAME = "idx_col_b";

    @Before
    public void setUp() throws SQLException {
        JdbcUtil.executeUpdateSuccess(tddlConnection,
            "DROP TABLE IF EXISTS " + TEST_TABLE);
    }

    @After
    public void tearDown() {
        JdbcUtil.executeUpdateSuccess(tddlConnection,
            "DROP TABLE IF EXISTS " + TEST_TABLE);
    }

    /**
     * Test physical_index_usage: one row per physical partition with raw values.
     */
    @Test
    public void testPhysicalIndexUsage() throws SQLException {
        createTestTable();
        generateIndexUsage();

        String sql = "SELECT * FROM information_schema.physical_index_usage "
            + "WHERE INDEX_NAME = '" + LOCAL_INDEX_NAME + "'";
        ResultSet rs = JdbcUtil.executeQuery(sql, tddlConnection);

        int rowCount = 0;
        while (rs.next()) {
            String indexName = rs.getString("INDEX_NAME");
            long countStar = rs.getLong("COUNT_STAR");
            long countFetch = rs.getLong("COUNT_FETCH");
            long sumTimerWait = rs.getLong("SUM_TIMER_WAIT");
            long maxTimerWait = rs.getLong("MAX_TIMER_WAIT");
            String logicalSchema = rs.getString("LOGICAL_SCHEMA");
            String logicalTable = rs.getString("LOGICAL_TABLE");

            Assert.assertEquals(LOCAL_INDEX_NAME, indexName);
            Assert.assertTrue("COUNT_STAR should be > 0", countStar > 0);
            Assert.assertTrue("COUNT_FETCH should be >= 0", countFetch >= 0);
            Assert.assertTrue("SUM_TIMER_WAIT should be >= 0", sumTimerWait >= 0);
            Assert.assertTrue("MAX_TIMER_WAIT should be >= 0", maxTimerWait >= 0);
            Assert.assertTrue("LOGICAL_SCHEMA should not be empty",
                StringUtils.isNotEmpty(logicalSchema));
            Assert.assertTrue("LOGICAL_TABLE should not be empty",
                StringUtils.isNotEmpty(logicalTable));

            rowCount++;
        }
        rs.close();

        Assert.assertTrue("Should have at least one physical partition row", rowCount > 0);
    }

    /**
     * Test logical_index_usage: aggregation across partitions.
     */
    @Test
    public void testLogicalIndexUsage() throws SQLException {
        createTestTable();
        generateIndexUsage();

        String sql = "SELECT * FROM information_schema.logical_index_usage "
            + "WHERE INDEX_NAME = '" + LOCAL_INDEX_NAME + "'"
            + " AND LOGICAL_TABLE = '" + TEST_TABLE + "'";
        ResultSet rs = JdbcUtil.executeQuery(sql, tddlConnection);

        boolean found = false;
        while (rs.next()) {
            String logicalSchema = rs.getString("LOGICAL_SCHEMA");
            String logicalTable = rs.getString("LOGICAL_TABLE");
            String gsiName = rs.getString("GSI_NAME");
            String indexName = rs.getString("INDEX_NAME");
            long totalUsage = rs.getLong("TOTAL_USAGE");
            long partCount = rs.getLong("PARTITION_COUNT");
            long avgUsage = rs.getLong("AVG_USAGE");
            long fetchCount = rs.getLong("COUNT_FETCH");
            long sumTimer = rs.getLong("SUM_TIMER_WAIT");
            long maxTimer = rs.getLong("MAX_TIMER_WAIT");

            Assert.assertTrue("LOGICAL_SCHEMA should not be empty",
                StringUtils.isNotEmpty(logicalSchema));
            Assert.assertEquals(TEST_TABLE.toLowerCase(), logicalTable.toLowerCase());
            Assert.assertEquals(LOCAL_INDEX_NAME, indexName);
            Assert.assertTrue("GSI_NAME should be empty for main table index",
                gsiName == null || gsiName.isEmpty());

            Assert.assertTrue("TOTAL_USAGE should be > 0", totalUsage > 0);
            Assert.assertTrue("PARTITION_COUNT should be > 0", partCount > 0);
            Assert.assertEquals("AVG_USAGE should be totalUsage/partitionCount",
                totalUsage / partCount, avgUsage);
            Assert.assertTrue("COUNT_FETCH should be >= 0", fetchCount >= 0);
            Assert.assertTrue("SUM_TIMER_WAIT should be >= 0", sumTimer >= 0);
            Assert.assertTrue("MAX_TIMER_WAIT should be >= 0", maxTimer >= 0);

            found = true;
        }
        rs.close();

        Assert.assertTrue("Should find at least one logical index usage row", found);
    }

    /**
     * Test CLEAR INDEX_USAGE: generate usage, clear, verify counters are reset.
     */
    @Test
    public void testClearIndexUsage() throws SQLException {
        createTestTable();
        generateIndexUsage();

        // Verify usage exists before clearing
        String checkSql = "SELECT SUM(COUNT_STAR) AS TOTAL FROM information_schema.physical_index_usage "
            + "WHERE INDEX_NAME = '" + LOCAL_INDEX_NAME + "'";
        ResultSet rs = JdbcUtil.executeQuery(checkSql, tddlConnection);
        Assert.assertTrue("Should have result before clear", rs.next());
        long totalBefore = rs.getLong("TOTAL");
        rs.close();
        Assert.assertTrue("COUNT_STAR sum should be > 0 before clear", totalBefore > 0);

        // Execute CLEAR INDEX_USAGE — returns OkPacket, not ResultSet
        JdbcUtil.executeUpdateSuccess(tddlConnection, "CLEAR INDEX_USAGE");

        // Verify usage is cleared — COUNT_STAR should be 0 for the test index
        ResultSet afterRs = JdbcUtil.executeQuery(checkSql, tddlConnection);
        if (afterRs.next()) {
            long totalAfter = afterRs.getLong("TOTAL");
            Assert.assertEquals("COUNT_STAR sum should be 0 after clear", 0, totalAfter);
        }
        afterRs.close();
    }

    /**
     * Test INDEX_USAGE_QUERY_TIMEOUT parameter: verify hint controls DN query timeout.
     */
    @Test
    public void testIndexUsageQueryTimeout() throws SQLException {
        createTestTable();
        generateIndexUsage();

        // Query with default timeout should return results
        String baseSql = "SELECT * FROM information_schema.physical_index_usage "
            + "WHERE INDEX_NAME = '" + LOCAL_INDEX_NAME + "'";
        ResultSet rs1 = JdbcUtil.executeQuery(baseSql, tddlConnection);
        int count1 = 0;
        while (rs1.next()) {
            count1++;
        }
        rs1.close();
        Assert.assertTrue("Should return results with default timeout", count1 > 0);

        // Query with custom timeout via hint should also work
        String hintSql = "/*+TDDL:cmd_extra(INDEX_USAGE_QUERY_TIMEOUT=30)*/ " + baseSql;
        ResultSet rs2 = JdbcUtil.executeQuery(hintSql, tddlConnection);
        int count2 = 0;
        while (rs2.next()) {
            count2++;
        }
        rs2.close();
        Assert.assertTrue("Should return results with custom timeout hint", count2 > 0);
        Assert.assertEquals("Row count should be same with or without hint", count1, count2);

        // Query with -1 timeout should fail with timeout error, proving the parameter takes effect
        String timeoutSql = "/*+TDDL:cmd_extra(INDEX_USAGE_QUERY_TIMEOUT=-1)*/ " + baseSql;
        try {
            Statement stmt = tddlConnection.createStatement();
            stmt.executeQuery(timeoutSql);
            Assert.fail("Query with INDEX_USAGE_QUERY_TIMEOUT=-1 should throw timeout exception");
        } catch (SQLException e) {
            Assert.assertTrue("Error should mention timeout",
                e.getMessage().contains("timed out"));
        }
    }

    // ==================== Helper methods ====================

    /**
     * Create a test table on CN with a local index and a GSI.
     */
    private void createTestTable() {
        String createSql = "CREATE TABLE " + TEST_TABLE + " (\n"
            + "  `id` bigint NOT NULL AUTO_INCREMENT,\n"
            + "  `col_a` bigint NOT NULL,\n"
            + "  `col_b` varchar(64) DEFAULT NULL,\n"
            + "  `col_c` int DEFAULT NULL,\n"
            + "  PRIMARY KEY (`id`),\n"
            + "  INDEX `" + LOCAL_INDEX_NAME + "` (`col_b`),\n"
            + "  GLOBAL INDEX `" + TEST_GSI + "` (`col_a`)"
            + " PARTITION BY KEY(`col_a`) PARTITIONS 4\n"
            + ") PARTITION BY KEY(`id`) PARTITIONS 4";
        JdbcUtil.executeUpdateSuccess(tddlConnection, createSql);
    }

    /**
     * Generate index usage by inserting data and running queries that use the local index.
     */
    private void generateIndexUsage() throws SQLException {
        for (int i = 0; i < 10; i++) {
            JdbcUtil.executeUpdateSuccess(tddlConnection,
                String.format("INSERT INTO %s (col_a, col_b, col_c) VALUES (%d, 'val_%d', %d)",
                    TEST_TABLE, i, i, i));
        }

        for (int i = 0; i < 5; i++) {
            ResultSet rs = JdbcUtil.executeQuery(
                "SELECT * FROM " + TEST_TABLE + " WHERE col_b = 'val_" + i + "'",
                tddlConnection);
            while (rs.next()) {
                // consume results to ensure DN executes the index lookup
            }
            rs.close();
        }
    }
}
