package com.alibaba.polardbx.optimizer.view;

import com.alibaba.polardbx.optimizer.PlannerContext;
import com.alibaba.polardbx.optimizer.config.meta.DrdsRelMetadataProvider;
import com.alibaba.polardbx.optimizer.config.meta.DrdsRelOptCostImpl;
import com.alibaba.polardbx.optimizer.core.DrdsConvention;
import org.apache.calcite.plan.ConventionTraitDef;
import org.apache.calcite.plan.RelOptCluster;
import org.apache.calcite.plan.RelOptCostFactory;
import org.apache.calcite.plan.RelOptPlanner;
import org.apache.calcite.plan.RelTraitSet;
import org.apache.calcite.plan.volcano.VolcanoPlanner;
import org.apache.calcite.rel.RelCollationTraitDef;
import org.apache.calcite.rel.RelDistributionTraitDef;
import org.apache.calcite.rel.type.RelDataType;
import org.apache.calcite.rel.type.RelDataTypeFactory;
import org.apache.calcite.rel.type.RelDataTypeField;
import org.apache.calcite.rel.type.RelDataTypeSystem;
import org.apache.calcite.rex.RexBuilder;
import org.apache.calcite.sql.type.SqlTypeFactoryImpl;
import org.apache.calcite.sql.type.SqlTypeName;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

// Generated By LLM
public class InformationSchemaCclBlockersTest {
    private RelOptCluster cluster;
    private RelTraitSet traitSet;
    private RelOptPlanner plannerMock;
    private RexBuilder rexBuilder;

    @Before
    public void setUp() {
        // Initialize the RelDataTypeFactory
        final RelDataTypeFactory typeFactory =
            new SqlTypeFactoryImpl(RelDataTypeSystem.DEFAULT);
        PlannerContext plannerContext = PlannerContext.EMPTY_CONTEXT;
        rexBuilder = new RexBuilder(typeFactory);
        RelOptCostFactory costFactory = DrdsRelOptCostImpl.FACTORY;
        plannerMock = new VolcanoPlanner(costFactory, plannerContext);
        plannerMock.clearRelTraitDefs();
        plannerMock.addRelTraitDef(ConventionTraitDef.INSTANCE);
        plannerMock.addRelTraitDef(RelCollationTraitDef.INSTANCE);
        plannerMock.addRelTraitDef(RelDistributionTraitDef.INSTANCE);
        cluster = RelOptCluster.create(plannerMock, rexBuilder);
        cluster.setMetadataProvider(DrdsRelMetadataProvider.INSTANCE);
        // Initialize the RelTraitSet with DrdsConvention.INSTANCE
        traitSet = RelTraitSet.createEmpty().replace(DrdsConvention.INSTANCE);
    }

    /**
     * Test the deriveRowType method to ensure that all columns are correctly defined.
     */
    @Test
    public void testDeriveRowType() {
        // Instantiate InformationSchemaCclBlockers using the first constructor
        InformationSchemaCclBlockers view = new InformationSchemaCclBlockers(cluster, traitSet);

        // Invoke deriveRowType
        RelDataType rowType = view.deriveRowType();

        // Retrieve the list of fields
        List<RelDataTypeField> fields = rowType.getFieldList();

        // Assert the number of columns
        assertEquals(InformationSchemaCclBlockers.CCL_BLOCKER_COLUMNS.length, fields.size());

        // Define expected column names in order
        List<String> expectedNames = Arrays.asList(InformationSchemaCclBlockers.CCL_BLOCKER_COLUMNS);

        // Define expected SQL types for each column
        List<SqlTypeName> expectedTypes = new ArrayList<>(Arrays.asList(
            SqlTypeName.BIGINT,    // NO.
            SqlTypeName.VARCHAR,   // TRIGGER_NAME
            SqlTypeName.VARCHAR,   // USER
            SqlTypeName.VARCHAR,   // HOST
            SqlTypeName.BIGINT,    // CCL_RULE_COUNT
            SqlTypeName.VARCHAR,   // DATABASE
            SqlTypeName.VARCHAR,   // CONDITIONS
            SqlTypeName.VARCHAR,   // RULE_CONFIG
            SqlTypeName.BIGINT,    // QUERY_RULE_UPGRADE
            SqlTypeName.BIGINT,    // MAX_CCL_RULE
            SqlTypeName.BIGINT,    // MAX_SQL_SIZE
            SqlTypeName.DATETIME   // CREATED_TIME
        ));

        // Iterate through each field and verify name and type
        for (int i = 0; i < fields.size(); i++) {
            RelDataTypeField field = fields.get(i);
            String expectedName = expectedNames.get(i);
            SqlTypeName expectedType = expectedTypes.get(i);

            assertEquals("Column name mismatch for index " + i, expectedName, field.getName());
            assertEquals("Type mismatch for column " + expectedName,
                expectedType, field.getType().getSqlTypeName());
        }
    }

    /**
     * Test that the InformationSchemaCclBlockers correctly handles empty RelTraitSet.
     */
    @Test
    public void testDeriveRowTypeWithEmptyTraitSet() {
        // Initialize an empty RelTraitSet
        RelTraitSet emptyTraitSet = RelTraitSet.createEmpty();

        // Instantiate InformationSchemaCclBlockers with empty trait set
        InformationSchemaCclBlockers view = new InformationSchemaCclBlockers(cluster, emptyTraitSet);

        // Invoke deriveRowType
        RelDataType rowType = view.deriveRowType();

        // Retrieve the list of fields
        List<RelDataTypeField> fields = rowType.getFieldList();

        // Assert the number of columns
        assertEquals(InformationSchemaCclBlockers.CCL_BLOCKER_COLUMNS.length, fields.size());
    }
}